### ISSUE TITLE
README improvement

### ISSUE THREAD

**Issue by ofedo** [chriszrc/ngx-stickyfill#2]
Hi, chriszrc!

Great work publishing this!
I wanted to use it, but couldn't figure out from where to import `NgxStickyfillModule` in `app.module.ts` :)) 

Also, i noticed a typo in the README.md at
https://github.com/chriszrc/ngx-stickyfill/tree/master/projects/ngx-stickyfill-lib
it's 
`npm install stickyfilljs --save`
instead of
`npm install stickfilljs --save`

Cheers!

**Comment by chriszrc** [comment]
Hi, 

Thanks for the heads up, I fixed the typo, and put in an example of the import. Let me know if you're still facing issues-

https://github.com/chriszrc/ngx-stickyfill/blob/master/projects/ngx-stickyfill-lib/README.md
